#Used by travis CI for testing

language: cpp

compiler:
  - gcc
  - clang
  
os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

before_install:
  - sudo apt-get install -qq libsdl2-dev libenet-dev libcereal-dev

before_script:
  - cmake .

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - cmake --build .
  - ctest --verbose
