#Used by travis CI for testing
dist: bionic

language: cpp

compiler:
  - gcc
  - clang
  
before_install:
  - sudo apt-get install -qq libsdl2-dev libenet-dev libcereal-dev libcurl4-openssl-dev libsdl2-image-dev libsdl2-image-2.0-0

before_script:
  - cmake .

script:
  - cmake --build .
  - ctest --verbose
