language: cpp

matrix:
  include:
    - name: "Bomberbloke on Linux"
    dist: bionic
    - name: "Bomberbloke on Windows"
    os: windows

compiler:
  - gcc
  - clang
 
before_install: sudo apt-get install -qq libsdl2-dev libenet-dev libcurl4-openssl-dev libsdl2-image-dev libsdl2-image-2.0-0 libsdl2-mixer-dev libsdl2-ttf-dev

before_script: cmake .

script:   
  - cmake --build .
  - ctest --verbose
