# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/joey/code/bomberbloke

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/joey/code/bomberbloke

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/joey/code/bomberbloke/CMakeFiles /home/joey/code/bomberbloke/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/joey/code/bomberbloke/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fmt

# Build rule for target.
fmt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fmt
.PHONY : fmt

# fast build rule for target.
fmt/fast:
	$(MAKE) -f CMakeFiles/fmt.dir/build.make CMakeFiles/fmt.dir/build
.PHONY : fmt/fast

#=============================================================================
# Target rules for targets named SHARED

# Build rule for target.
SHARED: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SHARED
.PHONY : SHARED

# fast build rule for target.
SHARED/fast:
	$(MAKE) -f CMakeFiles/SHARED.dir/build.make CMakeFiles/SHARED.dir/build
.PHONY : SHARED/fast

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

engine/actor/actor.o: engine/actor/actor.cpp.o

.PHONY : engine/actor/actor.o

# target to build an object file
engine/actor/actor.cpp.o:
	$(MAKE) -f CMakeFiles/SHARED.dir/build.make CMakeFiles/SHARED.dir/engine/actor/actor.cpp.o
.PHONY : engine/actor/actor.cpp.o

engine/actor/actor.i: engine/actor/actor.cpp.i

.PHONY : engine/actor/actor.i

# target to preprocess a source file
engine/actor/actor.cpp.i:
	$(MAKE) -f CMakeFiles/SHARED.dir/build.make CMakeFiles/SHARED.dir/engine/actor/actor.cpp.i
.PHONY : engine/actor/actor.cpp.i

engine/actor/actor.s: engine/actor/actor.cpp.s

.PHONY : engine/actor/actor.s

# target to generate assembly for a file
engine/actor/actor.cpp.s:
	$(MAKE) -f CMakeFiles/SHARED.dir/build.make CMakeFiles/SHARED.dir/engine/actor/actor.cpp.s
.PHONY : engine/actor/actor.cpp.s

engine/client.o: engine/client.cpp.o

.PHONY : engine/client.o

# target to build an object file
engine/client.cpp.o:
	$(MAKE) -f CMakeFiles/SHARED.dir/build.make CMakeFiles/SHARED.dir/engine/client.cpp.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/engine/client.cpp.o
.PHONY : engine/client.cpp.o

engine/client.i: engine/client.cpp.i

.PHONY : engine/client.i

# target to preprocess a source file
engine/client.cpp.i:
	$(MAKE) -f CMakeFiles/SHARED.dir/build.make CMakeFiles/SHARED.dir/engine/client.cpp.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/engine/client.cpp.i
.PHONY : engine/client.cpp.i

engine/client.s: engine/client.cpp.s

.PHONY : engine/client.s

# target to generate assembly for a file
engine/client.cpp.s:
	$(MAKE) -f CMakeFiles/SHARED.dir/build.make CMakeFiles/SHARED.dir/engine/client.cpp.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/engine/client.cpp.s
.PHONY : engine/client.cpp.s

engine/control/controls.o: engine/control/controls.cpp.o

.PHONY : engine/control/controls.o

# target to build an object file
engine/control/controls.cpp.o:
	$(MAKE) -f CMakeFiles/SHARED.dir/build.make CMakeFiles/SHARED.dir/engine/control/controls.cpp.o
.PHONY : engine/control/controls.cpp.o

engine/control/controls.i: engine/control/controls.cpp.i

.PHONY : engine/control/controls.i

# target to preprocess a source file
engine/control/controls.cpp.i:
	$(MAKE) -f CMakeFiles/SHARED.dir/build.make CMakeFiles/SHARED.dir/engine/control/controls.cpp.i
.PHONY : engine/control/controls.cpp.i

engine/control/controls.s: engine/control/controls.cpp.s

.PHONY : engine/control/controls.s

# target to generate assembly for a file
engine/control/controls.cpp.s:
	$(MAKE) -f CMakeFiles/SHARED.dir/build.make CMakeFiles/SHARED.dir/engine/control/controls.cpp.s
.PHONY : engine/control/controls.cpp.s

engine/engine.o: engine/engine.cpp.o

.PHONY : engine/engine.o

# target to build an object file
engine/engine.cpp.o:
	$(MAKE) -f CMakeFiles/SHARED.dir/build.make CMakeFiles/SHARED.dir/engine/engine.cpp.o
.PHONY : engine/engine.cpp.o

engine/engine.i: engine/engine.cpp.i

.PHONY : engine/engine.i

# target to preprocess a source file
engine/engine.cpp.i:
	$(MAKE) -f CMakeFiles/SHARED.dir/build.make CMakeFiles/SHARED.dir/engine/engine.cpp.i
.PHONY : engine/engine.cpp.i

engine/engine.s: engine/engine.cpp.s

.PHONY : engine/engine.s

# target to generate assembly for a file
engine/engine.cpp.s:
	$(MAKE) -f CMakeFiles/SHARED.dir/build.make CMakeFiles/SHARED.dir/engine/engine.cpp.s
.PHONY : engine/engine.cpp.s

engine/level/level.o: engine/level/level.cpp.o

.PHONY : engine/level/level.o

# target to build an object file
engine/level/level.cpp.o:
	$(MAKE) -f CMakeFiles/SHARED.dir/build.make CMakeFiles/SHARED.dir/engine/level/level.cpp.o
.PHONY : engine/level/level.cpp.o

engine/level/level.i: engine/level/level.cpp.i

.PHONY : engine/level/level.i

# target to preprocess a source file
engine/level/level.cpp.i:
	$(MAKE) -f CMakeFiles/SHARED.dir/build.make CMakeFiles/SHARED.dir/engine/level/level.cpp.i
.PHONY : engine/level/level.cpp.i

engine/level/level.s: engine/level/level.cpp.s

.PHONY : engine/level/level.s

# target to generate assembly for a file
engine/level/level.cpp.s:
	$(MAKE) -f CMakeFiles/SHARED.dir/build.make CMakeFiles/SHARED.dir/engine/level/level.cpp.s
.PHONY : engine/level/level.cpp.s

engine/player/player.o: engine/player/player.cpp.o

.PHONY : engine/player/player.o

# target to build an object file
engine/player/player.cpp.o:
	$(MAKE) -f CMakeFiles/SHARED.dir/build.make CMakeFiles/SHARED.dir/engine/player/player.cpp.o
.PHONY : engine/player/player.cpp.o

engine/player/player.i: engine/player/player.cpp.i

.PHONY : engine/player/player.i

# target to preprocess a source file
engine/player/player.cpp.i:
	$(MAKE) -f CMakeFiles/SHARED.dir/build.make CMakeFiles/SHARED.dir/engine/player/player.cpp.i
.PHONY : engine/player/player.cpp.i

engine/player/player.s: engine/player/player.cpp.s

.PHONY : engine/player/player.s

# target to generate assembly for a file
engine/player/player.cpp.s:
	$(MAKE) -f CMakeFiles/SHARED.dir/build.make CMakeFiles/SHARED.dir/engine/player/player.cpp.s
.PHONY : engine/player/player.cpp.s

engine/server.o: engine/server.cpp.o

.PHONY : engine/server.o

# target to build an object file
engine/server.cpp.o:
	$(MAKE) -f CMakeFiles/SHARED.dir/build.make CMakeFiles/SHARED.dir/engine/server.cpp.o
.PHONY : engine/server.cpp.o

engine/server.i: engine/server.cpp.i

.PHONY : engine/server.i

# target to preprocess a source file
engine/server.cpp.i:
	$(MAKE) -f CMakeFiles/SHARED.dir/build.make CMakeFiles/SHARED.dir/engine/server.cpp.i
.PHONY : engine/server.cpp.i

engine/server.s: engine/server.cpp.s

.PHONY : engine/server.s

# target to generate assembly for a file
engine/server.cpp.s:
	$(MAKE) -f CMakeFiles/SHARED.dir/build.make CMakeFiles/SHARED.dir/engine/server.cpp.s
.PHONY : engine/server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... fmt"
	@echo "... edit_cache"
	@echo "... SHARED"
	@echo "... client"
	@echo "... engine/actor/actor.o"
	@echo "... engine/actor/actor.i"
	@echo "... engine/actor/actor.s"
	@echo "... engine/client.o"
	@echo "... engine/client.i"
	@echo "... engine/client.s"
	@echo "... engine/control/controls.o"
	@echo "... engine/control/controls.i"
	@echo "... engine/control/controls.s"
	@echo "... engine/engine.o"
	@echo "... engine/engine.i"
	@echo "... engine/engine.s"
	@echo "... engine/level/level.o"
	@echo "... engine/level/level.i"
	@echo "... engine/level/level.s"
	@echo "... engine/player/player.o"
	@echo "... engine/player/player.i"
	@echo "... engine/player/player.s"
	@echo "... engine/server.o"
	@echo "... engine/server.i"
	@echo "... engine/server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

