# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/joey/code/bomberbloke

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/joey/code/bomberbloke

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/joey/code/bomberbloke/CMakeFiles /home/joey/code/bomberbloke/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/joey/code/bomberbloke/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fmt

# Build rule for target.
fmt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fmt
.PHONY : fmt

# fast build rule for target.
fmt/fast:
	$(MAKE) -f CMakeFiles/fmt.dir/build.make CMakeFiles/fmt.dir/build
.PHONY : fmt/fast

#=============================================================================
# Target rules for targets named CLIENT_ENGINE

# Build rule for target.
CLIENT_ENGINE: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CLIENT_ENGINE
.PHONY : CLIENT_ENGINE

# fast build rule for target.
CLIENT_ENGINE/fast:
	$(MAKE) -f CMakeFiles/CLIENT_ENGINE.dir/build.make CMakeFiles/CLIENT_ENGINE.dir/build
.PHONY : CLIENT_ENGINE/fast

#=============================================================================
# Target rules for targets named bomberbloke_client

# Build rule for target.
bomberbloke_client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bomberbloke_client
.PHONY : bomberbloke_client

# fast build rule for target.
bomberbloke_client/fast:
	$(MAKE) -f CMakeFiles/bomberbloke_client.dir/build.make CMakeFiles/bomberbloke_client.dir/build
.PHONY : bomberbloke_client/fast

client/bomberbloke.o: client/bomberbloke.cpp.o

.PHONY : client/bomberbloke.o

# target to build an object file
client/bomberbloke.cpp.o:
	$(MAKE) -f CMakeFiles/bomberbloke_client.dir/build.make CMakeFiles/bomberbloke_client.dir/client/bomberbloke.cpp.o
.PHONY : client/bomberbloke.cpp.o

client/bomberbloke.i: client/bomberbloke.cpp.i

.PHONY : client/bomberbloke.i

# target to preprocess a source file
client/bomberbloke.cpp.i:
	$(MAKE) -f CMakeFiles/bomberbloke_client.dir/build.make CMakeFiles/bomberbloke_client.dir/client/bomberbloke.cpp.i
.PHONY : client/bomberbloke.cpp.i

client/bomberbloke.s: client/bomberbloke.cpp.s

.PHONY : client/bomberbloke.s

# target to generate assembly for a file
client/bomberbloke.cpp.s:
	$(MAKE) -f CMakeFiles/bomberbloke_client.dir/build.make CMakeFiles/bomberbloke_client.dir/client/bomberbloke.cpp.s
.PHONY : client/bomberbloke.cpp.s

common/bloke.o: common/bloke.cpp.o

.PHONY : common/bloke.o

# target to build an object file
common/bloke.cpp.o:
	$(MAKE) -f CMakeFiles/CLIENT_ENGINE.dir/build.make CMakeFiles/CLIENT_ENGINE.dir/common/bloke.cpp.o
.PHONY : common/bloke.cpp.o

common/bloke.i: common/bloke.cpp.i

.PHONY : common/bloke.i

# target to preprocess a source file
common/bloke.cpp.i:
	$(MAKE) -f CMakeFiles/CLIENT_ENGINE.dir/build.make CMakeFiles/CLIENT_ENGINE.dir/common/bloke.cpp.i
.PHONY : common/bloke.cpp.i

common/bloke.s: common/bloke.cpp.s

.PHONY : common/bloke.s

# target to generate assembly for a file
common/bloke.cpp.s:
	$(MAKE) -f CMakeFiles/CLIENT_ENGINE.dir/build.make CMakeFiles/CLIENT_ENGINE.dir/common/bloke.cpp.s
.PHONY : common/bloke.cpp.s

common/bomb.o: common/bomb.cpp.o

.PHONY : common/bomb.o

# target to build an object file
common/bomb.cpp.o:
	$(MAKE) -f CMakeFiles/CLIENT_ENGINE.dir/build.make CMakeFiles/CLIENT_ENGINE.dir/common/bomb.cpp.o
.PHONY : common/bomb.cpp.o

common/bomb.i: common/bomb.cpp.i

.PHONY : common/bomb.i

# target to preprocess a source file
common/bomb.cpp.i:
	$(MAKE) -f CMakeFiles/CLIENT_ENGINE.dir/build.make CMakeFiles/CLIENT_ENGINE.dir/common/bomb.cpp.i
.PHONY : common/bomb.cpp.i

common/bomb.s: common/bomb.cpp.s

.PHONY : common/bomb.s

# target to generate assembly for a file
common/bomb.cpp.s:
	$(MAKE) -f CMakeFiles/CLIENT_ENGINE.dir/build.make CMakeFiles/CLIENT_ENGINE.dir/common/bomb.cpp.s
.PHONY : common/bomb.cpp.s

engine/actor/actor.o: engine/actor/actor.cpp.o

.PHONY : engine/actor/actor.o

# target to build an object file
engine/actor/actor.cpp.o:
	$(MAKE) -f CMakeFiles/CLIENT_ENGINE.dir/build.make CMakeFiles/CLIENT_ENGINE.dir/engine/actor/actor.cpp.o
.PHONY : engine/actor/actor.cpp.o

engine/actor/actor.i: engine/actor/actor.cpp.i

.PHONY : engine/actor/actor.i

# target to preprocess a source file
engine/actor/actor.cpp.i:
	$(MAKE) -f CMakeFiles/CLIENT_ENGINE.dir/build.make CMakeFiles/CLIENT_ENGINE.dir/engine/actor/actor.cpp.i
.PHONY : engine/actor/actor.cpp.i

engine/actor/actor.s: engine/actor/actor.cpp.s

.PHONY : engine/actor/actor.s

# target to generate assembly for a file
engine/actor/actor.cpp.s:
	$(MAKE) -f CMakeFiles/CLIENT_ENGINE.dir/build.make CMakeFiles/CLIENT_ENGINE.dir/engine/actor/actor.cpp.s
.PHONY : engine/actor/actor.cpp.s

engine/client.o: engine/client.cpp.o

.PHONY : engine/client.o

# target to build an object file
engine/client.cpp.o:
	$(MAKE) -f CMakeFiles/CLIENT_ENGINE.dir/build.make CMakeFiles/CLIENT_ENGINE.dir/engine/client.cpp.o
.PHONY : engine/client.cpp.o

engine/client.i: engine/client.cpp.i

.PHONY : engine/client.i

# target to preprocess a source file
engine/client.cpp.i:
	$(MAKE) -f CMakeFiles/CLIENT_ENGINE.dir/build.make CMakeFiles/CLIENT_ENGINE.dir/engine/client.cpp.i
.PHONY : engine/client.cpp.i

engine/client.s: engine/client.cpp.s

.PHONY : engine/client.s

# target to generate assembly for a file
engine/client.cpp.s:
	$(MAKE) -f CMakeFiles/CLIENT_ENGINE.dir/build.make CMakeFiles/CLIENT_ENGINE.dir/engine/client.cpp.s
.PHONY : engine/client.cpp.s

engine/control/controls.o: engine/control/controls.cpp.o

.PHONY : engine/control/controls.o

# target to build an object file
engine/control/controls.cpp.o:
	$(MAKE) -f CMakeFiles/CLIENT_ENGINE.dir/build.make CMakeFiles/CLIENT_ENGINE.dir/engine/control/controls.cpp.o
.PHONY : engine/control/controls.cpp.o

engine/control/controls.i: engine/control/controls.cpp.i

.PHONY : engine/control/controls.i

# target to preprocess a source file
engine/control/controls.cpp.i:
	$(MAKE) -f CMakeFiles/CLIENT_ENGINE.dir/build.make CMakeFiles/CLIENT_ENGINE.dir/engine/control/controls.cpp.i
.PHONY : engine/control/controls.cpp.i

engine/control/controls.s: engine/control/controls.cpp.s

.PHONY : engine/control/controls.s

# target to generate assembly for a file
engine/control/controls.cpp.s:
	$(MAKE) -f CMakeFiles/CLIENT_ENGINE.dir/build.make CMakeFiles/CLIENT_ENGINE.dir/engine/control/controls.cpp.s
.PHONY : engine/control/controls.cpp.s

engine/engine.o: engine/engine.cpp.o

.PHONY : engine/engine.o

# target to build an object file
engine/engine.cpp.o:
	$(MAKE) -f CMakeFiles/CLIENT_ENGINE.dir/build.make CMakeFiles/CLIENT_ENGINE.dir/engine/engine.cpp.o
.PHONY : engine/engine.cpp.o

engine/engine.i: engine/engine.cpp.i

.PHONY : engine/engine.i

# target to preprocess a source file
engine/engine.cpp.i:
	$(MAKE) -f CMakeFiles/CLIENT_ENGINE.dir/build.make CMakeFiles/CLIENT_ENGINE.dir/engine/engine.cpp.i
.PHONY : engine/engine.cpp.i

engine/engine.s: engine/engine.cpp.s

.PHONY : engine/engine.s

# target to generate assembly for a file
engine/engine.cpp.s:
	$(MAKE) -f CMakeFiles/CLIENT_ENGINE.dir/build.make CMakeFiles/CLIENT_ENGINE.dir/engine/engine.cpp.s
.PHONY : engine/engine.cpp.s

engine/level/level.o: engine/level/level.cpp.o

.PHONY : engine/level/level.o

# target to build an object file
engine/level/level.cpp.o:
	$(MAKE) -f CMakeFiles/CLIENT_ENGINE.dir/build.make CMakeFiles/CLIENT_ENGINE.dir/engine/level/level.cpp.o
.PHONY : engine/level/level.cpp.o

engine/level/level.i: engine/level/level.cpp.i

.PHONY : engine/level/level.i

# target to preprocess a source file
engine/level/level.cpp.i:
	$(MAKE) -f CMakeFiles/CLIENT_ENGINE.dir/build.make CMakeFiles/CLIENT_ENGINE.dir/engine/level/level.cpp.i
.PHONY : engine/level/level.cpp.i

engine/level/level.s: engine/level/level.cpp.s

.PHONY : engine/level/level.s

# target to generate assembly for a file
engine/level/level.cpp.s:
	$(MAKE) -f CMakeFiles/CLIENT_ENGINE.dir/build.make CMakeFiles/CLIENT_ENGINE.dir/engine/level/level.cpp.s
.PHONY : engine/level/level.cpp.s

engine/player/player.o: engine/player/player.cpp.o

.PHONY : engine/player/player.o

# target to build an object file
engine/player/player.cpp.o:
	$(MAKE) -f CMakeFiles/CLIENT_ENGINE.dir/build.make CMakeFiles/CLIENT_ENGINE.dir/engine/player/player.cpp.o
.PHONY : engine/player/player.cpp.o

engine/player/player.i: engine/player/player.cpp.i

.PHONY : engine/player/player.i

# target to preprocess a source file
engine/player/player.cpp.i:
	$(MAKE) -f CMakeFiles/CLIENT_ENGINE.dir/build.make CMakeFiles/CLIENT_ENGINE.dir/engine/player/player.cpp.i
.PHONY : engine/player/player.cpp.i

engine/player/player.s: engine/player/player.cpp.s

.PHONY : engine/player/player.s

# target to generate assembly for a file
engine/player/player.cpp.s:
	$(MAKE) -f CMakeFiles/CLIENT_ENGINE.dir/build.make CMakeFiles/CLIENT_ENGINE.dir/engine/player/player.cpp.s
.PHONY : engine/player/player.cpp.s

engine/server.o: engine/server.cpp.o

.PHONY : engine/server.o

# target to build an object file
engine/server.cpp.o:
	$(MAKE) -f CMakeFiles/CLIENT_ENGINE.dir/build.make CMakeFiles/CLIENT_ENGINE.dir/engine/server.cpp.o
.PHONY : engine/server.cpp.o

engine/server.i: engine/server.cpp.i

.PHONY : engine/server.i

# target to preprocess a source file
engine/server.cpp.i:
	$(MAKE) -f CMakeFiles/CLIENT_ENGINE.dir/build.make CMakeFiles/CLIENT_ENGINE.dir/engine/server.cpp.i
.PHONY : engine/server.cpp.i

engine/server.s: engine/server.cpp.s

.PHONY : engine/server.s

# target to generate assembly for a file
engine/server.cpp.s:
	$(MAKE) -f CMakeFiles/CLIENT_ENGINE.dir/build.make CMakeFiles/CLIENT_ENGINE.dir/engine/server.cpp.s
.PHONY : engine/server.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... fmt"
	@echo "... CLIENT_ENGINE"
	@echo "... bomberbloke_client"
	@echo "... client/bomberbloke.o"
	@echo "... client/bomberbloke.i"
	@echo "... client/bomberbloke.s"
	@echo "... common/bloke.o"
	@echo "... common/bloke.i"
	@echo "... common/bloke.s"
	@echo "... common/bomb.o"
	@echo "... common/bomb.i"
	@echo "... common/bomb.s"
	@echo "... engine/actor/actor.o"
	@echo "... engine/actor/actor.i"
	@echo "... engine/actor/actor.s"
	@echo "... engine/client.o"
	@echo "... engine/client.i"
	@echo "... engine/client.s"
	@echo "... engine/control/controls.o"
	@echo "... engine/control/controls.i"
	@echo "... engine/control/controls.s"
	@echo "... engine/engine.o"
	@echo "... engine/engine.i"
	@echo "... engine/engine.s"
	@echo "... engine/level/level.o"
	@echo "... engine/level/level.i"
	@echo "... engine/level/level.s"
	@echo "... engine/player/player.o"
	@echo "... engine/player/player.i"
	@echo "... engine/player/player.s"
	@echo "... engine/server.o"
	@echo "... engine/server.i"
	@echo "... engine/server.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

